# Generated by Django 3.1.7 on 2021-04-04 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0001_initial'),
        ('crimes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='suspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='suspects.suspect'),
        ),
    ]
