# Generated by Django 3.1.7 on 2021-04-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0003_auto_20210405_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='color',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6),
        ),
    ]
