# Generated by Django 3.1.7 on 2021-04-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0005_auto_20210408_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='crime_type',
            field=models.CharField(choices=[('Aggravated Assault', 'Aggravated Assault'), ('Kidnapping', 'Kidnapping'), ('Arson', 'Arson'), ('Assault', 'Assault'), ('Bribery', 'Bribery'), ('Burglary', 'Burglary'), ('Insurance Fraud', 'Insurance Fraud'), ('Open Container', 'Open Container'), ('Computer Crime', 'Computer Crime'), ('Credit Fraud', 'Credit Fraud'), ('Public Intoxication', 'Public Intoxication'), ('Cyberbullying', 'Cyberbullying'), ('Robbery', 'Robbery'), ('Stalking', 'Stalking'), ('Forgery', 'Forgery'), ('Harassment', 'Harassment'), ('Theft', 'Theft'), ('Vandalism', 'Vandalism'), ('Indecent Exposure', 'Indecent Exposure')], default='theft', max_length=200),
        ),
    ]
