# Generated by Django 3.1.7 on 2021-04-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0006_auto_20210408_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='crime_type',
            field=models.CharField(choices=[('Assault', 'Assault'), ('Computer Crime', 'Computer Crime'), ('Insurance Fraud', 'Insurance Fraud'), ('Stalking', 'Stalking'), ('Arson', 'Arson'), ('Credit Fraud', 'Credit Fraud'), ('Forgery', 'Forgery'), ('Harassment', 'Harassment'), ('Aggravated Assault', 'Aggravated Assault'), ('Kidnapping', 'Kidnapping'), ('Open Container', 'Open Container'), ('Cyberbullying', 'Cyberbullying'), ('Vandalism', 'Vandalism'), ('Indecent Exposure', 'Indecent Exposure'), ('Theft', 'Theft'), ('Burglary', 'Burglary'), ('Farts', 'Farts'), ('Bribery', 'Bribery'), ('Robbery', 'Robbery'), ('Public Intoxication', 'Public Intoxication')], default='theft', max_length=200),
        ),
    ]
