# Generated by Django 3.2 on 2021-04-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0009_crime_reported_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
