# Generated by Django 3.2 on 2021-04-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimes', '0010_alter_crime_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
