[phases.setup]

packages = [
  "gcc",         
  "libpq",          
  "postgresql.dev", 
  "zlib",          
  "zlib.dev",      
  "libjpeg",       
  "libjpeg.dev",
]

[phases.build]
[phases.install]