# Generated by Django 3.1.7 on 2021-04-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='mugshot',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
