# Generated by Django 3.1.7 on 2021-04-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0002_auto_20210406_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='mugshot',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
