# Generated by Django 3.1.7 on 2021-04-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0003_auto_20210406_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='in_custody',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
