# Generated by Django 3.1.7 on 2021-04-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0004_auto_20210409_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='in_custody',
            field=models.BooleanField(default=False),
        ),
    ]
