# Generated by Django 3.2 on 2021-04-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0006_suspect_reported_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
