# Generated by Django 3.2 on 2021-04-25 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suspects', '0007_alter_suspect_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspect',
            name='spotted',
            field=models.ManyToManyField(blank=True, related_name='spotted_suspect', to=settings.AUTH_USER_MODEL),
        ),
    ]
