# Generated by Django 3.2 on 2021-04-26 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suspects', '0008_suspect_spotted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspect',
            name='spotted',
        ),
        migrations.AddField(
            model_name='suspect',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_suspect', to=settings.AUTH_USER_MODEL),
        ),
    ]
