# Generated by Django 3.2 on 2021-04-26 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suspects', '0010_auto_20210426_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='spotted',
            field=models.ManyToManyField(blank=True, related_name='spot_suspect', to=settings.AUTH_USER_MODEL),
        ),
    ]
