# Generated by Django 4.1.7 on 2023-05-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suspects', '0012_auto_20210625_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
