CRIME_CHOICES = (
        ('NA', 'NA'),
        ('Aggravated Assault', 'Aggravated Assault'),
        ('Kidnapping', 'Kidnapping'),
        ('Arson', 'Arson'),
        ('Assault', 'Assault'),
        ('Bribery', 'Bribery'),
        ('Burglary', 'Burglary'),
        ('Insurance Fraud', 'Insurance Fraud'),
        ('Open Container', 'Open Container'),
        ('Computer Crime', 'Computer Crime'),
        ('Credit Fraud', 'Credit Fraud'),
        ('Public Intoxication', 'Public Intoxication'),
        ('Cyberbullying', 'Cyberbullying'),
        ('Robbery', 'Robbery'),
        ('Stalking', 'Stalking'),
        ('Forgery', 'Forgery'),
        ('Harassment', 'Harassment'),
        ('Theft', 'Theft'),
        ('Vandalism', 'Vandalism'),
        ('Indecent Exposure', 'Indecent Exposure'),
)


STATE_CHOICES = (
        ('NA', 'NA'),
        ('AK', 'Alaska'),
        ('AL', 'Alabama'),
        ('AR', 'Arkansas'),
        ('AS', 'American Samoa'),
        ('AZ', 'Arizona'),
        ('CA', 'California'),
        ('CO', 'Colorado'),
        ('CT', 'Connecticut'),
        ('DC', 'District of Columbia'),
        ('DE', 'Delaware'),
        ('FL', 'Florida'),
        ('GA', 'Georgia'),
        ('GU', 'Guam'),
        ('HI', 'Hawaii'),
        ('IA', 'Iowa'),
        ('ID', 'Idaho'),
        ('IL', 'Illinois'),
        ('IN', 'Indiana'),
        ('KS', 'Kansas'),
        ('KY', 'Kentucky'),
        ('LA', 'Louisiana'),
        ('MA', 'Massachusetts'),
        ('MD', 'Maryland'),
        ('ME', 'Maine'),
        ('MI', 'Michigan'),
        ('MN', 'Minnesota'),
        ('MO', 'Missouri'),
        ('MP', 'Northern Mariana Islands'),
        ('MS', 'Mississippi'),
        ('MT', 'Montana'),
        ('NA', 'National'),
        ('NC', 'North Carolina'),
        ('ND', 'North Dakota'),
        ('NE', 'Nebraska'),
        ('NH', 'New Hampshire'),
        ('NJ', 'New Jersey'),
        ('NM', 'New Mexico'),
        ('NV', 'Nevada'),
        ('NY', 'New York'),
        ('OH', 'Ohio'),
        ('OK', 'Oklahoma'),
        ('OR', 'Oregon'),
        ('PA', 'Pennsylvania'),
        ('PR', 'Puerto Rico'),
        ('RI', 'Rhode Island'),
        ('SC', 'South Carolina'),
        ('SD', 'South Dakota'),
        ('TN', 'Tennessee'),
        ('TX', 'Texas'),
        ('UT', 'Utah'),
        ('VA', 'Virginia'),
        ('VI', 'Virgin Islands'),
        ('VT', 'Vermont'),
        ('WA', 'Washington'),
        ('WI', 'Wisconsin'),
        ('WV', 'West Virginia'),
        ('WY', 'Wyoming'),
)

